### ISSUE TITLE
Präsentation Vorbereiten

### ISSUE THREAD

**Issue by MaxTrautwein** [MaxTrautwein/AStA-Digital-Forms#22]
Zwischenpräsentation Vorbereiten
- Vorläufige Fassung bis Sa Morgen
- Endgültig bis Di Vormittag

**Comment by MaxTrautwein** [comment]
Angegeben auf Moodle.
Da Quelle nicht als Datei verfügbar (Formatierung passt beim Export in .odp nicht) in Form von Link beigefügt

**Comment by MaxTrautwein** [comment]
Time spent für Erstellen, verbessern & Üben 3h

**Comment by Ebenezer2077** [comment]
Arbeitszeit ingesammt ca 3 Stunden

**Comment by HydroZocker** [comment]
Time spent für Erstellen, verbessern, üben und Bearbeitung einer Illustration 4h
