### ISSUE TITLE
Klickdummy bauen

### ISSUE THREAD

**Issue by MaxTrautwein** [MaxTrautwein/AStA-Digital-Forms#25]
Figma...

**Comment by Ebenezer2077** [comment]
Arbeitszeit: 1h

**Comment by Ebenezer2077** [comment]
collapsable Favoriten und fertige Antrräge fertig, Arbeitszeit 15 min

**Comment by Ebenezer2077** [comment]
Burger menü funktionabel Arbeitszeit 45 min

**Comment by Ebenezer2077** [comment]
Account and Settings mocked Arbeitszeit: 30 min

**Comment by Ebenezer2077** [comment]
integration des Reisekosten erstattungsantrags zu demonstrationszwecken 20% abgeschlossen. Arbeitszeit 1h

**Comment by Ebenezer2077** [comment]
integration des Reisekosten erstattungsantrags zu demonstrationszwecken 70% abgeschlossen. Arbeitszeit 15 min

**Comment by Ebenezer2077** [comment]
finished Antrag Implementierung, began with progression bar. Arbeitszeit: 30 min

**Comment by Ebenezer2077** [comment]
Finished progression Bar, solved some layer bugs. Arbeitszeit 45 minutes:
NOTE: If the "Vorschuss gezahlt" checkbox isn't working, try reload the prototype. Figma seems not to like this one XD

**Comment by MaxTrautwein** [comment]
we should probably close this.
it is clearly done
