### ISSUE TITLE
Interviews Vorbereiten

### ISSUE THREAD

**Issue by MaxTrautwein** [MaxTrautwein/AStA-Digital-Forms#26]
Fragen Erstellen

**Comment by HydroZocker** [comment]
1h für Fragen bzw. ersten Entwurf

**Comment by HydroZocker** [comment]
1.	Wie finden Sie die Farbumgebung?


2.	Wie finden Sie die Bedienung?


3.	Können Sie mir beschreiben, wie Sie die Anwendung verwenden würden, um Formulare zu auszufüllen?


4.	Wie hat sich die Anwendung im Vergleich zur manuellen Bearbeitung von Formularen für Sie ausgewirkt? Haben Sie Zeit gespart? Einfacher als das manuelle ausfüllen?


5.	Wie würden Sie die Gesamtnutzungserfahrung mit der Anwendung beschreiben?


6.	Wie würden Sie die Lernkurve für die Verwendung der Anwendung bewerten? Gab es etwas, das Sie verwirrt hat oder das Sie gerne einfacher gehabt hätten?

7.	Auf welche Schwierigkeiten sind Sie bei der Nutzung der Anwendung gestoßen? Gibt es Bereiche, die verbessert werden könnten?

8.	Welche Funktionen der App finden Sie besonders nützlich für Ihre spezifischen Anforderungen?

9.	Sonstige Anmerkungen:
