### ISSUE TITLE
Interviews

### ISSUE THREAD

**Issue by MaxTrautwein** [MaxTrautwein/AStA-Digital-Forms#27]
Durchführen
Auswerten

depends on #26 & #25

**Comment by MaxTrautwein** [comment]
Spent 30 Minutes Interviewing
4 Personen aus 2 Fachschaften

**Comment by HydroZocker** [comment]
30min Auswertung Interviews.
https://md.fachschaften.org/mpvekTRiQ_-8qIiSf5-EBw?edit
