### ISSUE TITLE
Setup Installations- und Administrationshandbuch

### ISSUE THREAD

**Issue by MaxTrautwein** [MaxTrautwein/AStA-Digital-Forms#39]

**Comment by Ebenezer2077** [comment]
Erster Schritt ist gemacht. es müsste noch einiges an unnötigem Code in dem Latex file sein, weil ich das template von der Docu übernommen habe. Kann man in Zukunft noch rausschmeißen, ist aber kein Muss.

**Comment by MaxTrautwein** [comment]
Als Readme
Anhängen Config Dateien Erstellen & Verwenden

**Comment by MaxTrautwein** [comment]
Die Doku findet sich in der wiki unter: https://github.com/MaxTrautwein/AStA-Digital-Forms/wiki
1h 45min
derzeitiger stand

**Comment by MaxTrautwein** [comment]
https://github.com/MaxTrautwein/AStA-Digital-Forms/wiki/PDF-Export
https://github.com/MaxTrautwein/AStA-Digital-Forms/wiki/Formular-Konfiguration
Still need more work. 
Possibly some code updates.

https://github.com/MaxTrautwein/AStA-Digital-Forms/wiki/Deployment-%E2%80%90-Domain-&-Hosting#note
Might also demand some updates to the deployment scripts
Spent 30 minutes

**Comment by MaxTrautwein** [comment]
Updated https://github.com/MaxTrautwein/AStA-Digital-Forms/wiki/Formular-Konfiguration
Spent 1h 5min

**Comment by MaxTrautwein** [comment]
Spent 1h 15min
