### ISSUE TITLE
Doku & Planung - Funktionsumfang & Aufwandsschätzung

### ISSUE THREAD

**Issue by MaxTrautwein** [MaxTrautwein/AStA-Digital-Forms#7]
Detail-Planung in Meeting am 3.4.24 ab 14:30

**Comment by MaxTrautwein** [comment]
Die Requirements sowie die konzeptionelle Schätzung haben wir im Team gemeinsame bearbeitet.
Dafür haben wir 8 Stunden Zeit aufgewendet.

Diese Ergebnisse müssen nun noch mit in die Dokumentation aufgenommen werden und teilweise näher beschrieben werden.

**Comment by MaxTrautwein** [comment]
Ich habe für die Übernahme und erste Formatierung 15 min in a9f432b1e058e11e2145ac55200b7c1ca37c00b8 aufgewendet

**Comment by MaxTrautwein** [comment]
spent another 15min on ebc9a5683c1366e3c72093a40b7153ac1c90c6d1

**Comment by MaxTrautwein** [comment]
spent 1h and 45 Minuets on 7dd4fe16e2d2c9de6f888c78817e57314fcf3e4e.
With most of the time going towards setting up the Table and helper command

**Comment by MaxTrautwein** [comment]
Spent 45 Minutes on 9b9ac0fb27cb6a84b2bf02fa5a7e4f354c3bf9cb

**Comment by MaxTrautwein** [comment]
Spend 45 Minutes on 0bd3e71d69446ac8853b493a1b2eeb8ed8fa4bfb

**Comment by MaxTrautwein** [comment]
Spent 1h and 15 Minutes on 5ee79772a2a75b879341b2634234aaaad7753e90

**Comment by MaxTrautwein** [comment]
Spent 30 Minutes on 99fd4a75bff4e49e7131d5644abc955fe4efaf47

**Comment by MaxTrautwein** [comment]
Spent 15 Minutes on 0727037364a33b7689480f17afee59f3b0c040e2

**Comment by HydroZocker** [comment]
Aufwand 2h von mir

**Comment by MaxTrautwein** [comment]
Spent 15 Minutes with my grammar issues
