### ISSUE TITLE
Api Spec Doku Update

### ISSUE THREAD

**Issue by MaxTrautwein** [MaxTrautwein/AStA-Digital-Forms#74]
- Beschreibungen in der Spec
- TeX Doku Updaten
- Swagger 2 PDF (Das wie Dokumentieren)
- (Testen) Obs was für pdf anhang in TeX gibt

PDF wird bei der Issue Hochgeladen

**Comment by MaxTrautwein** [comment]
Form auf Seite 5 schaut richtig wild aus.
Eventuell besser im Querformat?

Wäre cool, wenn wir den Editor auf Seite 1 nicht sehen müssten

**Comment by Ebenezer2077** [comment]
[API Spec.pdf](https://github.com/MaxTrautwein/AStA-Digital-Forms/files/15417494/API.Spec.pdf)
So besser?

**Comment by MaxTrautwein** [comment]
Auf jeden Fall besser.
Schade das die breite nicht besser ausgenutzt wird

**Comment by Ebenezer2077** [comment]
finde da auf die schnelle keine Einstellung dafür, aber dann mach ich mal damit weiter

**Comment by Ebenezer2077** [comment]
[API Spec2.pdf](https://github.com/MaxTrautwein/AStA-Digital-Forms/files/15421561/API.Spec2.pdf)
finale PDF (wichtig, da sonst die änderungen von Latex nicht mitgenommen werrden)

**Comment by Ebenezer2077** [comment]
[API_Spec.pdf](https://github.com/MaxTrautwein/AStA-Digital-Forms/files/15421611/API_Spec.pdf)
finale PDF (wichtig, da sonst die änderungen von Latex nicht mitgenommen werrden)

**Comment by Ebenezer2077** [comment]
PDF Generierung:

1.    Openapi.yaml in Swagger editor einfügen
2.    Alle cards ausklappen
3.    Seite als PDF drucken(in Firefox)
4.    Tob Bar des Editors mit weißem Quadrat überdecken
5.    Seite erneut als PDF speichern(damit änderung wirksam wird)
6.    erzeugtes PDF in Latex anhängen

**Comment by MaxTrautwein** [comment]
resolved with https://github.com/MaxTrautwein/AStA-Digital-Forms/pull/80
