### ISSUE TITLE
Feature Speichern (+ Laden im Backend & API)

### ISSUE THREAD

**Issue by MaxTrautwein** [MaxTrautwein/AStA-Digital-Forms#75]

**Comment by MaxTrautwein** [comment]
I a bit uncertain how to best handle Forms vs Templates
I see two Options:
1. Keep the Template Data in the Form
2. Only keep: ID, Data and ref to Template

**Comment by MaxTrautwein** [comment]
Spent 1.5H

**Comment by MaxTrautwein** [comment]
Spent 2h developing and Testing function to get the User.
Time also needed for frontend test code that will not be committed

**Comment by Sn1p3rr3c0n** [comment]
Spent 3h Implementing the Backend API

**Comment by MaxTrautwein** [comment]
Spent 3h Adding the backend API

**Comment by MaxTrautwein** [comment]
Spent 4h adding autosave to the frontend
Encountered an odd issue where PUT causes an CORS error but GET & POST work fine

**Comment by MaxTrautwein** [comment]
That appears to align with https://spring.io/blog/2015/06/08/cors-support-in-spring-framework#global-cors-configuration
Seems that even if we specify CORS in the Spec, we still need to allow other methods explicitly.
Needs Testing

**Comment by MaxTrautwein** [comment]
spent 15 min
