### ISSUE TITLE
Doku - Projektmanagement

### ISSUE THREAD

**Issue by MaxTrautwein** [MaxTrautwein/AStA-Digital-Forms#8]
Dokumentation für das Kapitel `Projektmanagement` erstellen.
Mit den Unterpunkten:

- Methode
- Lizenz
- Github Flow

**Comment by Sn1p3rr3c0n** [comment]
## Definition of Done
Im Team besprochen vorerst:

- Funktionen funktionsfähig und vollständig
- Code sinnvoll kommentiert
- Tests erstellt
- Tests Passen
- Dokumentation Geschrieben

**Comment by MaxTrautwein** [comment]
## Definition of Done
Im Team besprochen vorerst:

- Funktionen funktionsfähig und vollständig
- Code sinnvoll kommentiert
- Tests erstellt
- Tests Passen
- Dokumentation Geschrieben

**Comment by HydroZocker** [comment]
4h Aufwand Gesamt mit Korrektur
